trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  ACR_NAME: techwithdiwana.azurecr.io
  IMAGE_TAG: $(Build.BuildId)

steps:

# ==========================================
# Build & Push Backend
# ==========================================

- task: Docker@2
  displayName: Build and Push Backend
  inputs:
    command: buildAndPush
    repository: backend
    dockerfile: backend/Dockerfile
    containerRegistry: techwithdiwana-serviceconnection
    tags: |
      $(IMAGE_TAG)

# ==========================================
# Build & Push Frontend
# ==========================================

- task: Docker@2
  displayName: Build and Push Frontend
  inputs:
    command: buildAndPush
    repository: frontend
    dockerfile: frontend/Dockerfile
    containerRegistry: techwithdiwana-serviceconnection
    tags: |
      $(IMAGE_TAG)

# ==========================================
# Install kubectl
# ==========================================

- task: KubectlInstaller@0
  inputs:
    kubectlVersion: latest

# ==========================================
# Login to AKS
# ==========================================

- task: AzureCLI@2
  displayName: Login to AKS
  inputs:
    azureSubscription: Azure Resource Manager
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az aks get-credentials \
      --resource-group aks-free-rg \
      --name free-aks \
      --overwrite-existing

# ==========================================
# Update Backend Image
# ==========================================

- script: |
    kubectl set image deployment/backend-deployment \
    backend=$(ACR_NAME)/backend:$(IMAGE_TAG)

  displayName: Update Backend Image

# ==========================================
# Update Frontend Image
# ==========================================

- script: |
    kubectl set image deployment/frontend-deployment \
    frontend=$(ACR_NAME)/frontend:$(IMAGE_TAG)

  displayName: Update Frontend Image

# ==========================================
# Verify Rollout
# ==========================================

- script: |
    kubectl rollout status deployment/backend-deployment
    kubectl rollout status deployment/frontend-deployment

  displayName: Verify Rollout

# ==========================================
# Verify Cluster
# ==========================================

- script: |
    kubectl get pods
    kubectl get svc
    kubectl get ingress

  displayName: Verify AKS Deployment